Add deprecated Django admin image used by app
Needs to be found otherwise template include will not render with a
ValueError: Missing staticfiles manifest entry